import{i as n,a as y,S as m}from"./assets/vendor-DEenWwFD.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();console.log("merhaba");const h="48479056-b624f953eac1ddf8407abd187",b="https://pixabay.com/api/",v=document.querySelector(".search-input"),L=document.querySelector(".search-btn"),d=document.querySelector(".images-container"),l=document.querySelector(".loader"),a=document.querySelector(".load-more-btn");let u=1,S=40,p="",g=0;L.addEventListener("click",()=>{const o=v.value.trim();o?(p=o,d.innerHTML="",f(o),g=0):n.warning({message:"Please enter a search term.",position:"topRight"})});function P(o){return new URLSearchParams({key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:S,page:u}).toString()}async function f(o){const i=`${b}?${P(o)}`;l.style.visibility="visible";try{const s=await y.get(i);s.data.hits.length>0?w(s.data.hits):n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a.style.visibility="visible",g>=s.data.totalHits&&(a.style.display="none",n.info({message:"Tüm resimler yüklendi! Başka sonuç yok.",position:"topRight"}))}catch(s){n.error({message:"We're sorry, but you've reached the end of search results",position:"topRight"}),a.style.visibility="hidden",console.log("Hata :",s)}finally{l.style.visibility="hidden"}}a.addEventListener("click",()=>{l.style.visibility="visible",u++,f(p)});function w(o){const i=o.map(t=>`
        <div class="image-card">
       <a href="${t.largeImageURL}"> <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}"></a>
         <div class="info">
             <p><strong>Likes:</strong><br> ${t.likes}</br></p>
                    <p><strong>Views:</strong> <br>${t.views}</br></p>
                    <p><strong>Comments:</strong> <br>${t.comments}</br></p>
                    <p><strong>Downloads:</strong><br> ${t.downloads}</br></p>
                </div>
            </div>

        `).join("");d.insertAdjacentHTML("beforeend",i),new m(".image-card a",{captionsData:"alt",captionDelay:250,nav:!0}).refresh()}
//# sourceMappingURL=index.js.map
